services:

  python:
    image: osioaliu/crypto-prognose
    container_name: ${NAMESPACE}_python
#    build:
#      context: .docker/python
#      args:
#        PY_VERSION: ${PY_VERSION}
    working_dir: /usr/src/
    command: "tail -f /dev/null"
    volumes:
      - ./src:/usr/src